# Generated by Django 4.2.10 on 2024-02-09 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animalSpecie', models.CharField(max_length=10)),
                ('animalName', models.CharField(max_length=15)),
                ('animalAge', models.DecimalField(decimal_places=2, max_digits=4)),
                ('animalWidth', models.DecimalField(decimal_places=2, max_digits=4)),
                ('animalHeigh', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
    ]
