# Generated by Django 4.2.10 on 2024-02-09 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petshop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='animalAge',
        ),
        migrations.AddField(
            model_name='animal',
            name='animalBirth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
